openapi: 3.0.1
info:
  title: "WIP: Puppet Data Service API"
  description: "This is the API documentation for the Puppet Data Service API. You can find out more about the [PDS API at here](https://github.com/reidmv/reidmv-puppet_data_service). For this sample, you can use the api key `special-key` to test the authorization filters."
  termsOfService: http://swagger.io/terms/
  contact:
    email: solarch-team@puppet.com
  license:
    name: TBD
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: localhost:3000/v1
tags:
  - name: hiera-data
    description: Hiera data levels and key/value pairs
  - name: nodes
    description: Node details and configuration data, Nodedata stores configuration details for a specific node and Hierdata manages your Hiera Key:Value as a service
  - name: users
    description: Every config change should be started with an authorized User
    externalDocs:
      description: TBD Find out more
      url: https://puppet.com/

paths:
  /users:
    get:
      tags:
        - users
      summary: Get all available users
      description: This can only be done by the logged in user with a superadmin role.
      operationId: getAllUsers
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
    post:
      tags:
        - users
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      requestBody:
        $ref: "#/components/requestBodies/NewUser"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
      x-codegen-request-body-name: body

  /users/{username}:
    get:
      tags:
        - users
      summary: Get user by username
      description: Retrieve a specific user.
      operationId: getUserByUsername
      parameters:
        - $ref: "#/components/parameters/Username"
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: "Invalid user supplied"
        "404":
          description: "User not found"

  /users/{username}/token:
    get:
      tags:
        - users
      summary: Get API token by username
      description: Retrieve an API token for the user
      operationId: getTokenByUsername
      parameters:
        - $ref: "#/components/parameters/Username"
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
        "400":
          description: "Invalid user supplied"
        "404":
          description: "User not found"

  /nodes:
    get:
      tags:
        - nodes
      summary: Get all available nodes
      description: This can only be done by the logged in user.
      operationId: getAllNodes
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Node"

  /nodes/{name}:
    get:
      tags:
        - nodes
      summary: Get node by node name
      description: Retrieve a specific node.
      operationId: getNodeByName
      parameters:
        - $ref: "#/components/parameters/NodeName"
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Node"
        "400":
          description: Invalid node-name supplied
        "404":
          description: Node not found

    put:
      tags:
        - nodes
      summary: Create a new node or replace an existing node
      description: This can only be done by the logged in user.
      operationId: putNodeByName
      parameters:
        - $ref: "#/components/parameters/NodeName"
      requestBody:
        $ref: "#/components/requestBodies/NewNode"
      responses:
        "200":
          description: Updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Node"
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Node"
        "400":
          description: Invalid node-name supplied
        "404":
          description: Node not found

    delete:
      tags:
        - nodes
      summary: Deletes a node
      description: This can only be done by the logged in user.
      operationId: deleteNode
      parameters:
        - $ref: "#/components/parameters/NodeName"
      responses:
        "200":
          description: Ok
          content: {}
        "400":
          description: Invalid Node name supplied
          content: {}
        "404":
          description: Nodedata not found
          content: {}

  /hiera/values:
    get:
      tags:
        - hiera-values
      summary: Get all hiera data values matching a filter
      description: Get all Hiera data values by level
      operationId: getHieraValues
      parameters:
        - $ref: "#/components/parameters/OptionalHieraLevel"
        - $ref: "#/components/parameters/OptionalHieraKey"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/HieraValue"

  /hiera/values/upsert:
    post:
      tags:
        - hiera-values
      summary: Set one or more Hiera values
      description: Set one or more Hiera values, using level, key, and value for each.
      operationId: upsertHieraValues
      requestBody:
        $ref: "#/components/requestBodies/EditHieraValues"
      responses:
        "204":
          $ref: "#/components/responses/204NoContent"

  /hiera/values/delete:
    post:
      tags:
        - hiera-values
      summary: Delete one or more Hiera values
      description: Delete one or more Hiera values, using level and key for each.
      operationId: deleteHieraValues
      requestBody:
        $ref: "#/components/requestBodies/ListHieraValues"
      responses:
        "204":
          $ref: "#/components/responses/204NoContent"

  /hiera/levels:
    get:
      tags:
        - hiera-levels
      summary: List all Hiera data levels
      description: List all levels for which Hiera data is defined
      operationId: getHieraLevels
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /hiera/level:
    get:
      tags:
        - hiera-levels
      summary: Get all hiera data values from a particular level
      description: Get all Hiera data values by level
      operationId: getHieraLevel
      parameters:
        - $ref: "#/components/parameters/HieraLevel"
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HieraLevel"

    put:
      tags:
        - hiera-levels
      summary: Get all hiera data values from a particular level
      description: Get all Hiera data values by level
      operationId: putHieraLevel
      parameters:
        - $ref: "#/components/parameters/HieraLevel"
      requestBody:
        $ref: "#/components/requestBodies/EditHieraLevel"
      responses:
        "204":
          $ref: "#/components/responses/204NoContent"

    delete:
      tags:
        - hiera-levels
      summary: Delete all hiera data values from a particular level
      description: Get all Hiera data values by level
      operationId: deleteHieraLevel
      parameters:
        - $ref: "#/components/parameters/HieraLevel"
      responses:
        "204":
          $ref: "#/components/responses/204NoContent"

components:
  schemas:
    Username:
      type: string
      pattern: '^([-\d\w.]+){2}$'

    TimestampProperties:
      type: object
      properties:
        created-at:
          type: string
          format: date-time
        updated-at:
          type: string
          format: date-time

    ImmutableUserProperties:
      type: object
      properties:
        username:
          $ref: "#/components/schemas/Username"

    EditableUserProperties:
      type: object
      properties:
        email:
          type: string
        role:
          type: string
          description: User role
          default: operator
          enum:
            - operator
            - superadmin
        status:
          type: string
          description: User status
          default: active
          enum:
            - active
            - inactive
            - deleted

    User:
      allOf:
        - $ref: "#/components/schemas/ImmutableUserProperties"
        - $ref: "#/components/schemas/EditableUserProperties"
        - $ref: "#/components/schemas/TimestampProperties"

    Token:
      type: object
      properties:
        token:
          type: string
          description: API token

    ImmutableNodeProperties:
      type: object
      properties:
        name:
          type: string

    EditableNodeProperties:
      type: object
      properties:
        code-environment:
          type: string
          description: Code environment
          enum:
            - staging
            - production
            - compliance
        classes:
          type: object
          additionalProperties:
            type: string
        trusted-data:
          type: object

    Node:
      allOf:
        - $ref: "#/components/schemas/ImmutableNodeProperties"
        - $ref: "#/components/schemas/EditableNodeProperties"
        - $ref: "#/components/schemas/TimestampProperties"

    ImmutableHieraValueProperties:
      type: object
      properties:
        level:
          type: string
        key:
          type: string

    EditableHieraValueProperties:
      type: object
      properties:
        value:
          nullable: true
          description: The value to set the Hiera key to

    HieraValue:
      allOf:
        - $ref: "#/components/schemas/ImmutableHieraValueProperties"
        - $ref: "#/components/schemas/EditableHieraValueProperties"
        - $ref: "#/components/schemas/TimestampProperties"

    HieraLevel:
      type: object
      description: Key-value pairs of Hiera data for a particular level
      properties:
        level:
          type: string
          description: The level of the data being returned
        data:
          type: object
          description: key-value pairs of Hiera data for the level
          additionalProperties:
            type: string

    # ApiResponse:
    #   type: object
    #   properties:
    #     code:
    #       type: integer
    #       format: int32
    #     type:
    #       type: string
    #     message:
    #       type: string

  parameters:
    Username:
      name: username
      in: path
      description: "The username"
      required: true
      schema:
        $ref: "#/components/schemas/Username"

    NodeName:
      name: name
      in: path
      description: "The node name to be fetched or modified. Use node1 for testing."
      required: true
      schema:
        type: string

    HieraLevel:
      name: level
      in: query
      description: "The Hiera level"
      required: true
      schema:
        type: string

    OptionalHieraLevel:
      name: key
      in: query
      description: "The Hiera key"
      required: false
      schema:
        type: string

    OptionalHieraKey:
      name: key
      in: query
      description: "The Hiera key"
      required: false
      schema:
        type: string

  requestBodies:
    NewUser:
      description: Create user object
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ImmutableUserProperties"
              - $ref: "#/components/schemas/EditableUserProperties"
              - required: ["username"]

    NewNode:
      description: Create node object
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ImmutableNodeProperties"
              - $ref: "#/components/schemas/EditableNodeProperties"
              - required: ["name"]

    EditNode:
      description: Edit existing node object
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/EditableNodeProperties"

    EditHieraValue:
      description: Create or edit a Hiera value at a specified level and key
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/EditableHieraValueProperties"
              - required: ["value"]

    EditHieraValues:
      description: Create or edit a set of Hiera values
      content:
        application/json:
          schema:
            type: array
            items:
              allOf:
                - $ref: "#/components/schemas/ImmutableHieraValueProperties"
                - $ref: "#/components/schemas/EditableHieraValueProperties"
                - required: ["level", "key", "value"]

    EditHieraLevel:
      description: Create or edit a set of Hiera values at a particular level
      content:
        application/json:
          schema:
            type: array
            items:
              allOf:
                - type: object
                  properties:
                    key:
                      type: string
                - $ref: "#/components/schemas/EditableHieraValueProperties"
                - required: ["key", "value"]

    ListHieraValues:
      description: List a set of Hiera values
      content:
        application/json:
          schema:
            type: array
            items:
              allOf:
                - $ref: "#/components/schemas/ImmutableHieraValueProperties"
                - required: ["level", "key"]

  responses:
    200Ok:
      description: Successful operation
      content: {}

    201Created:
      description: Successful operation
      content: {}

    204NoContent:
      description: No content

    HieraValue:
      description: successful operation
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HieraValue"

  securitySchemes:
    pds_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://tbd.swagger.io/oauth/dialog
          scopes:
            write:pets: modify data in your account
            read:pets: read your data
    api_key:
      type: apiKey
      name: api_key
      in: header
