#!/bin/sh

# This script provides an interface to rake commands that facilitate the
# administration of pds-service.

set -e

cd /opt/puppetlabs/server/apps/pds-service
/opt/puppetlabs/puppet/bin/bundle exec rake "$@"
